### ISSUE TITLE
ne compile pas !

### ISSUE THREAD

**Issue by opebayle** [jlngllt/terminal#1]
main.c: In function ‘read_key’:
main.c:342:12: error: ‘CTRL_K’ undeclared (first use in this function)
       case CTRL_K:
            ^
main.c:342:12: note: each undeclared identifier is reported only once for each function it appears in
make: *** [main.o] Erreur 1

**Comment by jlngllt** [comment]
Problème corrigé lors du commit https://github.com/jlngllt/terminal/commit/9946954f24f026a85e05391fdc8ff6b87b5f3393
